name: stack_answers_lite
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  flutter_login: ^3.1.0
  json_annotation: ^4.4.0
  uuid: 3.0.5

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  lints: 1.0.1

flutter: 
  uses-material-design: true

